# Generated by Django 4.0.10 on 2025-07-27 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='special_user',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
